# Docker Compose for Motif Studio

version: '3.8'
services:
  motifstudio-web:
    # Lives at ./motifstudio-web/Dockerfile
    build:
      context: ./motifstudio-web
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:7082
    ports:
      - "7080:80"
  motifstudio-server:
    # Lives at ./server
    build: ./server
    ports:
      - "7082:8000"


